### ISSUE TITLE
Questions about the update_s_q parameter

### ISSUE THREAD

**Issue by toooooodo** [tata1661/PAR-NeurIPS21#3]
Hi, thanks for releasing this elegant code. But I couldn't understand the `update_s_q` parameter a little bit. By reading the code I find that If it is `True`, in inner loop model is updated on support set and query set, and in outer loop model is updated on another support set and query set.  But why not update model on support set in inner loop and on query set in outer loop?  I don’t understand this point, and I don’t know if I understand it wrong.

**Comment by tata1661** [comment]
Sorry for the confusion. The previous version is mixed with our new trial where transfer learning between tasks is conducted. 
In PAR, we indeed calculate the inner loop loss on support set, and calculate the outer loop loss on all query sets of the meta-training tasks.  
Please see the update codes. 
Thanks for pointing this out! If you have further question, please feel free to open a new issue.
