### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by yaoman3** [tata1661/PAR-NeurIPS21#5]
Hi, we cannot reproduce the result you mention in your paper using your code. There is a huge gap between the output by this code and the result in the paper. Could you provide the setting that can reproduce the results? Thank you!

**Comment by toooooodo** [comment]
I have the same question too.

**Comment by tata1661** [comment]
Sorry. This is because that we mix an extension under development with the previous PAR. We now update the codes. 
All hyper-parameters are set as described in the paper (Appendix B). 
Please try the new codes instead.
