### ISSUE TITLE
Tox21数据集

### ISSUE THREAD

**Issue by Lirain21** [tata1661/PAR-NeurIPS21#8]
大家好，请问Tox21的数据集有达到论文中的精度嘛，参数是怎么设置的

**Comment by tata1661** [comment]
@Lirain21 For Tox21, the codes can reproduce the results reported in the paper:

| Tox21      | 10-shot     | 1-shot      |
|------------|-------------|-------------|
| Reported   | 84.93(0.11) | 83.01(0.09) |
| Reproduced | 85.01(0.18) | 83.47(0.19) |

 Please see the training logs below: 
[nohup_tox21tox21-_1shot_seed0.txt](https://github.com/tata1661/PAR-NeurIPS21/files/9019280/nohup_tox21tox21-_1shot_seed0.txt)
[nohup_tox21tox21-_1shot_seed1.txt](https://github.com/tata1661/PAR-NeurIPS21/files/9019282/nohup_tox21tox21-_1shot_seed1.txt)
[nohup_tox21tox21-_1shot_seed2.txt](https://github.com/tata1661/PAR-NeurIPS21/files/9019283/nohup_tox21tox21-_1shot_seed2.txt)
[nohup_tox21tox21-_10shot_seed0.txt](https://github.com/tata1661/PAR-NeurIPS21/files/9019284/nohup_tox21tox21-_10shot_seed0.txt)
[nohup_tox21tox21-_10shot_seed1.txt](https://github.com/tata1661/PAR-NeurIPS21/files/9019285/nohup_tox21tox21-_10shot_seed1.txt)
[nohup_tox21tox21-_10shot_seed2.txt](https://github.com/tata1661/PAR-NeurIPS21/files/9019286/nohup_tox21tox21-_10shot_seed2.txt)

**Comment by Lirain21** [comment]
Hello, @tata1661 , The above experimental settings are the experimental settings with respect to pretrain-GNN. I would like to know the settings for the no-pretrain experiment because the results in the paper are not reproduced in the case of no-pretrain, and I think it may be due to the parameter settings.
